// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTodoCreatedCode is the HTTP code returned for type PostTodoCreated
const PostTodoCreatedCode int = 201

/*PostTodoCreated Created

swagger:response postTodoCreated
*/
type PostTodoCreated struct {
}

// NewPostTodoCreated creates PostTodoCreated with default headers values
func NewPostTodoCreated() *PostTodoCreated {

	return &PostTodoCreated{}
}

// WriteResponse to the client
func (o *PostTodoCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
